### ISSUE TITLE
Program crashes when loading Texture Inspector on the Color/Split Texture Node

### ISSUE THREAD

**Issue by matthboers** [SprueKit/TexGraph#1]
Hey there, great project going on here!

Just a little bug report, when inspecting a split node from the color category, the program will crash consistently. Here is a screenshot of when it happens. 
![image](https://cloud.githubusercontent.com/assets/26402654/25016645/32d11f8e-2081-11e7-9fcc-3417a7e55b58.png)
Hope it helps. 

And since there isn't really a place where you can drop compliments, I wanted to say that the layout looks professional and pretty. Can't wait to see the future releases.

**Comment by SprueKit** [comment]
Thanks for the excellent bug report and useful screenshot.

This is fixed in the 0.2.1 hot-fix https://github.com/SprueKit/TexGraph/releases/tag/0.2.1 a proper installer and update process is in the works so hopefully in the near future it shouldn't be "oh, I have to download 60mb again and wipe out what I have." The update will not corrupt any of your texture graph XML files. For this fix all you really need is the EXE file.

If you have bandwidth caps or other issues, just let me know and I'll happily provide just the files you need in the interim.

You can also now use CTRL+SPACEBAR to bring up the Quick-Action menu while the Texture Graph is focused, where it will display the available texture nodes (with autocomplete text entry). It's an additional option vs the node-list, ribbon "Create" tab, and right-click context menu. A choose what's faster for you approach.

---

Development may look quite stagnant for a while, but projective painting like Substance Painter is coming as well as speedups for the blur, sobel-edge, and erosion nodes.
